version: '3.3'
services:
  db:
    image: mysql:8
    restart: always
    command: --init-file /data/application/init.sql --default-authentication-plugin=mysql_native_password


    environment:
      MYSQL_DATABASE: 'full-stack-ecommerce-liquibase'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'ecommerceappdocker'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'ecommerceappdocker'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'dockermysqlroot'

    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
      - ./init.sql:/data/application/init.sql


# Names our volume
volumes:
  my-db:

