# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  # action will be triggered on push to all branches 
  push:
    branches: 
      - "*"
  # action will be triggered on pull request to all branches  
  pull_request:
    branches: 
      - "*"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Step 1 - checkout branch from Github that triggered the action
        uses: actions/checkout@v2
        
      - name: Step 2 - set up Java 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'
           
      - name: Step 3 - Build Maven project
        run: mvn -B package --file pom.xml
